[package]
name = "rocket-app"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "^0.5.1", features = [ "json" ]}
serde_json = "^1.0.133"

[dev-dependencies]
rusty-hook = "^0.11.2"
